services:
- docker
language: minimal
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: dJHkP1kk6qnL3FXRrsFf8hRbMWxMGZ47rmOQWcKB3WZaxYlB9IjU7QOnayNYyP+/fC24kBYPg1ApSURZFhX87oNhsUEc0Cm9NfAk73oSrY6i4BZtKNM2xcEVY687XzFnGN/Qbh1RpGRYv8oxHpI8GT+NaIQNyhxySoQFvFKvY3u8tR6hiN/khQCZ/n9HzWqBrCN619yLySUovLX7XV9M/MdsuXDHah6hbDUmvWm4b5UoWsEn2BU8cj/nKy3PRD4AIm+ONq2iEcZk9/xzjUTELQuHA9XlR0Ue6+kfRarHIy1b3UPnMdj6hEhEgOZZCJMm9Z0y447anAVIak7Rt//B1sD8qhrCma7XPKEcHByPsmb7Bqq68kUStN2w54P6XKNB7VYfo+aD+qfWQLR8JLTjEcImzWyOBk1cDedSZjPlEZA3T6YBXyZiBTM1nMdzfqkVbcVq9N5x3ai4W3U5jBteX6WZinV+FgPEC7d//s+gNYWPJ8OWX6NXuHodJ34Z3T+OH7ob6wEzgLZ+hcDj2aBvO6Fu28BHi3j1Wvhi5lgjE4frWISJjg8BUqUtr/lNj02vx1Bgm3qDJEe4snVOpUTV6aBSH+sHsa8mX+txJ2ke2GFhGLImhxp1WZZhntZmSmUS0mcNSuXBR1FGSdeP8IqCzMbr6c5PJ7XohTkQ/cQcCak=
  - secure: Stg5jYDuPIi1gnkZY9BIrS93whruyiBBst6xHaBUeTD4igKO3ulSJpMbtFPNrcQ7G2VnauFCsCTlEfnYvsSsOLdu7nEHI7yNnCCJbpLTyP/ipqLvbQfYg4Gw05P5SUCoao7Pr8ZzeDyoU8sdjG1cH7iQRUr9ksKE2sPvtgPCW23HPXeOk+Y+jCFy32X4k0mDOMaZ0RXCh6spQ37V6BxsWlUZIusvzEre50uknjHsQBtVH3vPi85TFZGYMeL5lFhNmpU84K1oheK+s2m1tXGh33SCicJc9V0smtyn1f6VF+Y2t6LnrRO9QhjKn/2S1f5ltp6mVBHcCZJGNQrwC6NyoIIKS48QARRLaMYCDW3hJlgNzbXIbZCwYVsbcQFwZD7VRtqbyTtqWprDyZm3O5Rpk3uJlRCbXmstn08KbJmp266wQUveGzgaMkzZb+BZHKzxLWAICW1UH71dJqGAY7/F7OgvJIOZyAMSdcN5/VT0cCeL0U3Urmo97Wbt1DCINv9OijH4yJF5O7e+phutWuU1agN3TDxTbUCnJoDaC2hDl51h8QXsAADPE/bQzXTH5GFK0wPrkHIPuB8WP6OQgl5szId1xliHZI34CfGToxX+3a/WzCyktMWtCEVncSegK+OJBQavk26vF7h/tQOejVZmAhxdjz4SW5vzqUAXvlsPL+w=
notifications:
  email: false
  slack:
    secure: wiWFrSYLOp/UGHFpemvQTwZ87WclsdriRbyDWYmCysH1kmtHikh9hSIHWmHdiot5giUwLe9KPKkEMRLnUfgNg47h4cLogPluL01c3mgXM4Vt1uH2ZIKEwh2ezzMJAgKWNV56zOcUEldWRtBYIQXVfVcpcjydeTnRdjSmE14d4cJOQWAb3ysBdCJ0u/iP3YPrLTC+64mXtFYqE4CytL6koPvVLd4Nz8tOaih7Egv0I1PbWGROnolOnyHtq8PHiDcixBqJ9sktaamq8ImLolnRMQCNW3mmCZGysEPdbHcoGIIfIxo0D1P4uDFlZqzCsI3eRC0Q0i3vZfF/ha+fBCTaU2mLnjd5a1ABvZpncljpjbrXR1hflwsFrSHai8wuH2WGt7QVwfsWe8D9RbdeP39lq6DM1QFMV3izmJ0t2c+54j5ksHcqCbH/3dWtI3DJIweNa/I9A6/2YNkccX27eVkXqW5zco8ULz7CB1SD6L+hzcJAng1U0T3i6ecclrIfhfDZn3eE+8ktX2mvX+o39UZjsOHwcFZcJ54nXr+sv6Qo06EXEhtWlOcg+BQGH6F3b+slpHpi9DjDP7vviIoAaMVNrfmXXKfFYjqQhX3bhQIwbXOmVsh7Try6pGOEVhZp09s8VJA3PVYdLtWgsVexNZRIZd5UDKbNPHa1TOR3Ejb2HmM=
script:
- export REPO=xtradio/xtradio.org
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
after_success:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push $REPO:$TAG
- docker push $REPO:$COMMIT
